import Head from 'next/head';
const Home = () => {
  return (
    <div>
      <Head>
        <title>Stripe Navbar Clone</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1 className='text-lg'>Hello World</h1>
    </div>
  );
};

export default Home;
