import Head from 'next/head';
import Navbar from '../components/Navbar';
const Home = () => {
  return (
    <div>
      <Head>
        <title>Stripe Navbar Clone</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
    </div>
  );
};

export default Home;
